name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20

    - name: Install dependencies
      run: go mod tidy

    - name: Build the application
      run: go build -o drawio-converter

    - name: Test drawio conversion
      run: |
        ./drawio-converter assets/sample.drawio > assets/test_output.html
        diff assets/test_output.html assets/sample.html
