name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.24"

    - name: Build for Linux (amd64)
      run: |
        GOOS=linux GOARCH=amd64 go build -o drawio-converter-linux-amd64

    - name: Build for Linux (arm64)
      run: |
        GOOS=linux GOARCH=arm64 go build -o drawio-converter-linux-arm64

    - name: Build for Windows (amd64)
      run: |
        GOOS=windows GOARCH=amd64 go build -o drawio-converter-windows-amd64.exe

    - name: Build for Windows (arm64)
      run: |
        GOOS=windows GOARCH=arm64 go build -o drawio-converter-windows-arm64.exe

    - name: Build for macOS (amd64)
      run: |
        GOOS=darwin GOARCH=amd64 go build -o drawio-converter-macos-amd64

    - name: Build for macOS (arm64)
      run: |
        GOOS=darwin GOARCH=arm64 go build -o drawio-converter-macos-arm64

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Linux amd64 binary
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./drawio-converter-linux-amd64
        asset_name: drawio-converter-linux-amd64
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Linux arm64 binary
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./drawio-converter-linux-arm64
        asset_name: drawio-converter-linux-arm64
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Windows amd64 binary
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./drawio-converter-windows-amd64.exe
        asset_name: drawio-converter-windows-amd64.exe
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Windows arm64 binary
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./drawio-converter-windows-arm64.exe
        asset_name: drawio-converter-windows-arm64.exe
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload macOS amd64 binary
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./drawio-converter-macos-amd64
        asset_name: drawio-converter-macos-amd64
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload macOS arm64 binary
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./drawio-converter-macos-arm64
        asset_name: drawio-converter-macos-arm64
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  image-push:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        id: push_image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          # (repo-name):latest and (repo-name):(tag)
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:${{ github.ref_name }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:latest

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push_image.outputs.digest }}
          push-to-registry: true
